#ifndef CONFIG_H
#define CONFIG_H

#define CELL_SIZE_IN_PIXELS 64
#define GAME_WIDTH 24
#define GAME_HEIGHT 18
#define SDL_WINDOW_WIDTH (CELL_SIZE_IN_PIXELS * GAME_WIDTH)
#define SDL_WINDOW_HEIGHT (CELL_SIZE_IN_PIXELS * GAME_HEIGHT)
#define MINE_SPAWN_RATE 0.2f

#endif
